### ISSUE TITLE
Error in deploy 

### ISSUE THREAD

**Issue by IntelligenzaArtificiale** [asehmi/simple-streamlit-fastapi-integration#1]
![image](https://user-images.githubusercontent.com/108482353/230726352-8b74dcba-2b95-4d1f-bcdf-42a985b75cd2.png)

When deploy on streamlit cloud have this error ...

**Comment by asehmi** [comment]
There might be reserved ports in Streamlit Cloud, and also Streamlit Cloud isn't the best place to deploy non-Streamlit server apps, because clients won't be able to route ANY external requests to the server. I see on the Streamlit discussion forum you found a non-reserved port, but can't invoke the FastAPI docs URL. I [added a comment](https://discuss.streamlit.io/t/fastapi-and-streamlit-deploy-port-error/40980/4?u=asehmi) there.
